/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAddressProvider } from "./IAddressProvider";
export type { IAddressProviderEvents } from "./IAddressProviderEvents";
