/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICrediAccountExceptions } from "./ICrediAccountExceptions";
export type { ICreditAccount } from "./ICreditAccount";
