// SPDX-License-Identifier: BUSL-1.1
// Gearbox. Generalized leverage protocol that allows to take leverage and then use it across other DeFi protocols and platforms in a composable way.
// (c) Gearbox.fi, 2021
pragma solidity ^0.8.10;
import "../lib/test.sol";
import { CheatCodes, HEVM_ADDRESS } from "../lib/cheatCodes.sol";

/// @dev c-Tokens and LUNA are added for unit test purposes
enum Tokens {
    NO_TOKEN,
    cDAI,
    cUSDC,
    cUSDT,
    cLINK,
    LUNA,
    _1INCH,
    AAVE,
    COMP,
    CRV,
    DAI,
    DPI,
    FEI,
    LINK,
    SNX,
    UNI,
    USDC,
    USDT,
    WBTC,
    WETH,
    YFI,
    STETH,
    wstETH,
    CVX,
    FRAX,
    FXS,
    LDO,
    LUSD,
    sUSD,
    GUSD,
    LQTY,
    _3Crv,
    crvFRAX,
    steCRV,
    crvPlain3andSUSD,
    FRAX3CRV,
    LUSD3CRV,
    gusd3CRV,
    cvx3Crv,
    cvxcrvFRAX,
    cvxsteCRV,
    cvxFRAX3CRV,
    cvxLUSD3CRV,
    cvxcrvPlain3andSUSD,
    cvxgusd3CRV,
    stkcvx3Crv,
    stkcvxcrvFRAX,
    stkcvxsteCRV,
    stkcvxFRAX3CRV,
    stkcvxLUSD3CRV,
    stkcvxcrvPlain3andSUSD,
    stkcvxgusd3CRV,
    yvDAI,
    yvUSDC,
    yvWETH,
    yvWBTC,
    yvCurve_stETH,
    yvCurve_FRAX,
    dDAI,
    dUSDC,
    dWBTC,
    dWETH,
    GEAR
}
