/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type TokenBalanceStruct = {
  token: PromiseOrValue<string>;
  balance: PromiseOrValue<BigNumberish>;
  isAllowed: PromiseOrValue<boolean>;
  isEnabled: PromiseOrValue<boolean>;
};

export type TokenBalanceStructOutput = [string, BigNumber, boolean, boolean] & {
  token: string;
  balance: BigNumber;
  isAllowed: boolean;
  isEnabled: boolean;
};

export type CreditAccountDataStruct = {
  addr: PromiseOrValue<string>;
  borrower: PromiseOrValue<string>;
  inUse: PromiseOrValue<boolean>;
  creditManager: PromiseOrValue<string>;
  underlying: PromiseOrValue<string>;
  borrowedAmountPlusInterest: PromiseOrValue<BigNumberish>;
  borrowedAmountPlusInterestAndFees: PromiseOrValue<BigNumberish>;
  totalValue: PromiseOrValue<BigNumberish>;
  healthFactor: PromiseOrValue<BigNumberish>;
  borrowRate: PromiseOrValue<BigNumberish>;
  balances: TokenBalanceStruct[];
  repayAmount: PromiseOrValue<BigNumberish>;
  liquidationAmount: PromiseOrValue<BigNumberish>;
  canBeClosed: PromiseOrValue<boolean>;
  borrowedAmount: PromiseOrValue<BigNumberish>;
  cumulativeIndexAtOpen: PromiseOrValue<BigNumberish>;
  since: PromiseOrValue<BigNumberish>;
  version: PromiseOrValue<BigNumberish>;
  enabledTokenMask: PromiseOrValue<BigNumberish>;
};

export type CreditAccountDataStructOutput = [
  string,
  string,
  boolean,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  TokenBalanceStructOutput[],
  BigNumber,
  BigNumber,
  boolean,
  BigNumber,
  BigNumber,
  BigNumber,
  number,
  BigNumber
] & {
  addr: string;
  borrower: string;
  inUse: boolean;
  creditManager: string;
  underlying: string;
  borrowedAmountPlusInterest: BigNumber;
  borrowedAmountPlusInterestAndFees: BigNumber;
  totalValue: BigNumber;
  healthFactor: BigNumber;
  borrowRate: BigNumber;
  balances: TokenBalanceStructOutput[];
  repayAmount: BigNumber;
  liquidationAmount: BigNumber;
  canBeClosed: boolean;
  borrowedAmount: BigNumber;
  cumulativeIndexAtOpen: BigNumber;
  since: BigNumber;
  version: number;
  enabledTokenMask: BigNumber;
};

export type ContractAdapterStruct = {
  allowedContract: PromiseOrValue<string>;
  adapter: PromiseOrValue<string>;
};

export type ContractAdapterStructOutput = [string, string] & {
  allowedContract: string;
  adapter: string;
};

export type CreditManagerDataStruct = {
  addr: PromiseOrValue<string>;
  underlying: PromiseOrValue<string>;
  pool: PromiseOrValue<string>;
  isWETH: PromiseOrValue<boolean>;
  canBorrow: PromiseOrValue<boolean>;
  borrowRate: PromiseOrValue<BigNumberish>;
  minAmount: PromiseOrValue<BigNumberish>;
  maxAmount: PromiseOrValue<BigNumberish>;
  maxLeverageFactor: PromiseOrValue<BigNumberish>;
  availableLiquidity: PromiseOrValue<BigNumberish>;
  collateralTokens: PromiseOrValue<string>[];
  adapters: ContractAdapterStruct[];
  liquidationThresholds: PromiseOrValue<BigNumberish>[];
  version: PromiseOrValue<BigNumberish>;
  creditFacade: PromiseOrValue<string>;
  creditConfigurator: PromiseOrValue<string>;
  isDegenMode: PromiseOrValue<boolean>;
  degenNFT: PromiseOrValue<string>;
  isIncreaseDebtForbidden: PromiseOrValue<boolean>;
  forbiddenTokenMask: PromiseOrValue<BigNumberish>;
  maxEnabledTokensLength: PromiseOrValue<BigNumberish>;
  feeInterest: PromiseOrValue<BigNumberish>;
  feeLiquidation: PromiseOrValue<BigNumberish>;
  liquidationDiscount: PromiseOrValue<BigNumberish>;
  feeLiquidationExpired: PromiseOrValue<BigNumberish>;
  liquidationDiscountExpired: PromiseOrValue<BigNumberish>;
};

export type CreditManagerDataStructOutput = [
  string,
  string,
  string,
  boolean,
  boolean,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string[],
  ContractAdapterStructOutput[],
  BigNumber[],
  number,
  string,
  string,
  boolean,
  string,
  boolean,
  BigNumber,
  number,
  number,
  number,
  number,
  number,
  number
] & {
  addr: string;
  underlying: string;
  pool: string;
  isWETH: boolean;
  canBorrow: boolean;
  borrowRate: BigNumber;
  minAmount: BigNumber;
  maxAmount: BigNumber;
  maxLeverageFactor: BigNumber;
  availableLiquidity: BigNumber;
  collateralTokens: string[];
  adapters: ContractAdapterStructOutput[];
  liquidationThresholds: BigNumber[];
  version: number;
  creditFacade: string;
  creditConfigurator: string;
  isDegenMode: boolean;
  degenNFT: string;
  isIncreaseDebtForbidden: boolean;
  forbiddenTokenMask: BigNumber;
  maxEnabledTokensLength: number;
  feeInterest: number;
  feeLiquidation: number;
  liquidationDiscount: number;
  feeLiquidationExpired: number;
  liquidationDiscountExpired: number;
};

export type PoolDataStruct = {
  addr: PromiseOrValue<string>;
  isWETH: PromiseOrValue<boolean>;
  underlying: PromiseOrValue<string>;
  dieselToken: PromiseOrValue<string>;
  linearCumulativeIndex: PromiseOrValue<BigNumberish>;
  availableLiquidity: PromiseOrValue<BigNumberish>;
  expectedLiquidity: PromiseOrValue<BigNumberish>;
  expectedLiquidityLimit: PromiseOrValue<BigNumberish>;
  totalBorrowed: PromiseOrValue<BigNumberish>;
  depositAPY_RAY: PromiseOrValue<BigNumberish>;
  borrowAPY_RAY: PromiseOrValue<BigNumberish>;
  dieselRate_RAY: PromiseOrValue<BigNumberish>;
  withdrawFee: PromiseOrValue<BigNumberish>;
  cumulativeIndex_RAY: PromiseOrValue<BigNumberish>;
  timestampLU: PromiseOrValue<BigNumberish>;
  version: PromiseOrValue<BigNumberish>;
};

export type PoolDataStructOutput = [
  string,
  boolean,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  number
] & {
  addr: string;
  isWETH: boolean;
  underlying: string;
  dieselToken: string;
  linearCumulativeIndex: BigNumber;
  availableLiquidity: BigNumber;
  expectedLiquidity: BigNumber;
  expectedLiquidityLimit: BigNumber;
  totalBorrowed: BigNumber;
  depositAPY_RAY: BigNumber;
  borrowAPY_RAY: BigNumber;
  dieselRate_RAY: BigNumber;
  withdrawFee: BigNumber;
  cumulativeIndex_RAY: BigNumber;
  timestampLU: BigNumber;
  version: number;
};

export interface DataCompressorInterface extends utils.Interface {
  functions: {
    "WETHToken()": FunctionFragment;
    "addressProvider()": FunctionFragment;
    "contractsRegister()": FunctionFragment;
    "getAdapter(address,address)": FunctionFragment;
    "getCreditAccountData(address,address)": FunctionFragment;
    "getCreditAccountList(address)": FunctionFragment;
    "getCreditManagerData(address)": FunctionFragment;
    "getCreditManagersList()": FunctionFragment;
    "getPoolData(address)": FunctionFragment;
    "getPoolsList()": FunctionFragment;
    "hasOpenedCreditAccount(address,address)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "WETHToken"
      | "addressProvider"
      | "contractsRegister"
      | "getAdapter"
      | "getCreditAccountData"
      | "getCreditAccountList"
      | "getCreditManagerData"
      | "getCreditManagersList"
      | "getPoolData"
      | "getPoolsList"
      | "hasOpenedCreditAccount"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "WETHToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addressProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractsRegister",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAdapter",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditAccountData",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditAccountList",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditManagerData",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditManagersList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolData",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolsList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasOpenedCreditAccount",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "WETHToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addressProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractsRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdapter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreditAccountData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditAccountList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditManagerData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditManagersList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolsList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasOpenedCreditAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {};
}

export interface DataCompressor extends BaseContract {
  contractName: "DataCompressor";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DataCompressorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    WETHToken(overrides?: CallOverrides): Promise<[string]>;

    addressProvider(overrides?: CallOverrides): Promise<[string]>;

    contractsRegister(overrides?: CallOverrides): Promise<[string]>;

    getAdapter(
      _creditManager: PromiseOrValue<string>,
      _allowedContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { adapter: string }>;

    getCreditAccountData(
      _creditManager: PromiseOrValue<string>,
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [CreditAccountDataStructOutput] & {
        result: CreditAccountDataStructOutput;
      }
    >;

    getCreditAccountList(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [CreditAccountDataStructOutput[]] & {
        result: CreditAccountDataStructOutput[];
      }
    >;

    getCreditManagerData(
      _creditManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [CreditManagerDataStructOutput] & {
        result: CreditManagerDataStructOutput;
      }
    >;

    getCreditManagersList(
      overrides?: CallOverrides
    ): Promise<
      [CreditManagerDataStructOutput[]] & {
        result: CreditManagerDataStructOutput[];
      }
    >;

    getPoolData(
      _pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[PoolDataStructOutput] & { result: PoolDataStructOutput }>;

    getPoolsList(
      overrides?: CallOverrides
    ): Promise<[PoolDataStructOutput[]] & { result: PoolDataStructOutput[] }>;

    hasOpenedCreditAccount(
      _creditManager: PromiseOrValue<string>,
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    version(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  WETHToken(overrides?: CallOverrides): Promise<string>;

  addressProvider(overrides?: CallOverrides): Promise<string>;

  contractsRegister(overrides?: CallOverrides): Promise<string>;

  getAdapter(
    _creditManager: PromiseOrValue<string>,
    _allowedContract: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  getCreditAccountData(
    _creditManager: PromiseOrValue<string>,
    borrower: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<CreditAccountDataStructOutput>;

  getCreditAccountList(
    borrower: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<CreditAccountDataStructOutput[]>;

  getCreditManagerData(
    _creditManager: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<CreditManagerDataStructOutput>;

  getCreditManagersList(
    overrides?: CallOverrides
  ): Promise<CreditManagerDataStructOutput[]>;

  getPoolData(
    _pool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<PoolDataStructOutput>;

  getPoolsList(overrides?: CallOverrides): Promise<PoolDataStructOutput[]>;

  hasOpenedCreditAccount(
    _creditManager: PromiseOrValue<string>,
    borrower: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  version(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    WETHToken(overrides?: CallOverrides): Promise<string>;

    addressProvider(overrides?: CallOverrides): Promise<string>;

    contractsRegister(overrides?: CallOverrides): Promise<string>;

    getAdapter(
      _creditManager: PromiseOrValue<string>,
      _allowedContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    getCreditAccountData(
      _creditManager: PromiseOrValue<string>,
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<CreditAccountDataStructOutput>;

    getCreditAccountList(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<CreditAccountDataStructOutput[]>;

    getCreditManagerData(
      _creditManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<CreditManagerDataStructOutput>;

    getCreditManagersList(
      overrides?: CallOverrides
    ): Promise<CreditManagerDataStructOutput[]>;

    getPoolData(
      _pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PoolDataStructOutput>;

    getPoolsList(overrides?: CallOverrides): Promise<PoolDataStructOutput[]>;

    hasOpenedCreditAccount(
      _creditManager: PromiseOrValue<string>,
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    WETHToken(overrides?: CallOverrides): Promise<BigNumber>;

    addressProvider(overrides?: CallOverrides): Promise<BigNumber>;

    contractsRegister(overrides?: CallOverrides): Promise<BigNumber>;

    getAdapter(
      _creditManager: PromiseOrValue<string>,
      _allowedContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreditAccountData(
      _creditManager: PromiseOrValue<string>,
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreditAccountList(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreditManagerData(
      _creditManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreditManagersList(overrides?: CallOverrides): Promise<BigNumber>;

    getPoolData(
      _pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPoolsList(overrides?: CallOverrides): Promise<BigNumber>;

    hasOpenedCreditAccount(
      _creditManager: PromiseOrValue<string>,
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    WETHToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addressProvider(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contractsRegister(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAdapter(
      _creditManager: PromiseOrValue<string>,
      _allowedContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreditAccountData(
      _creditManager: PromiseOrValue<string>,
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreditAccountList(
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreditManagerData(
      _creditManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreditManagersList(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPoolData(
      _pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPoolsList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasOpenedCreditAccount(
      _creditManager: PromiseOrValue<string>,
      borrower: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
