/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721ReceiverMock } from "./ERC721ReceiverMock";
export type { IERC721Receiver } from "./IERC721Receiver";
