/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICreditManagerV2Exceptions,
  ICreditManagerV2ExceptionsInterface,
} from "../../ICreditManagerV2.sol/ICreditManagerV2Exceptions";

const _abi = [
  {
    inputs: [],
    name: "AdaptersOrCreditFacadeOnlyException",
    type: "error",
  },
  {
    inputs: [],
    name: "AllowanceFailedException",
    type: "error",
  },
  {
    inputs: [],
    name: "CreditConfiguratorOnlyException",
    type: "error",
  },
  {
    inputs: [],
    name: "CreditFacadeOnlyException",
    type: "error",
  },
  {
    inputs: [],
    name: "HasNoOpenedAccountException",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughCollateralException",
    type: "error",
  },
  {
    inputs: [],
    name: "ReentrancyLockException",
    type: "error",
  },
  {
    inputs: [],
    name: "TargetContractNotAllowedException",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenAlreadyAddedException",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenNotAllowedException",
    type: "error",
  },
  {
    inputs: [],
    name: "TooManyEnabledTokensException",
    type: "error",
  },
  {
    inputs: [],
    name: "TooManyTokensException",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddressOrUserAlreadyHasAccountException",
    type: "error",
  },
] as const;

export class ICreditManagerV2Exceptions__factory {
  static readonly abi = _abi;
  static createInterface(): ICreditManagerV2ExceptionsInterface {
    return new utils.Interface(_abi) as ICreditManagerV2ExceptionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICreditManagerV2Exceptions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICreditManagerV2Exceptions;
  }
}
