/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPriceOracle } from "./IPriceOracle";
export type { IPriceOracleV2 } from "./IPriceOracleV2";
export type { IPriceOracleV2Events } from "./IPriceOracleV2Events";
export type { IPriceOracleV2Exceptions } from "./IPriceOracleV2Exceptions";
export type { IPriceOracleV2Ext } from "./IPriceOracleV2Ext";
