/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ICreditConfiguratorInterface extends utils.Interface {
  functions: {
    "addCollateralToken(address,uint16)": FunctionFragment;
    "addEmergencyLiquidator(address)": FunctionFragment;
    "addressProvider()": FunctionFragment;
    "allowContract(address,address)": FunctionFragment;
    "allowToken(address)": FunctionFragment;
    "allowedContracts()": FunctionFragment;
    "creditFacade()": FunctionFragment;
    "creditManager()": FunctionFragment;
    "forbidAdapter(address)": FunctionFragment;
    "forbidContract(address)": FunctionFragment;
    "forbidToken(address)": FunctionFragment;
    "removeEmergencyLiquidator(address)": FunctionFragment;
    "setExpirationDate(uint40)": FunctionFragment;
    "setFees(uint16,uint16,uint16,uint16,uint16)": FunctionFragment;
    "setIncreaseDebtForbidden(bool)": FunctionFragment;
    "setLimitPerBlock(uint128)": FunctionFragment;
    "setLimits(uint128,uint128)": FunctionFragment;
    "setLiquidationThreshold(address,uint16)": FunctionFragment;
    "setMaxEnabledTokens(uint8)": FunctionFragment;
    "underlying()": FunctionFragment;
    "upgradeCreditConfigurator(address)": FunctionFragment;
    "upgradeCreditFacade(address,bool)": FunctionFragment;
    "upgradePriceOracle()": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addCollateralToken"
      | "addEmergencyLiquidator"
      | "addressProvider"
      | "allowContract"
      | "allowToken"
      | "allowedContracts"
      | "creditFacade"
      | "creditManager"
      | "forbidAdapter"
      | "forbidContract"
      | "forbidToken"
      | "removeEmergencyLiquidator"
      | "setExpirationDate"
      | "setFees"
      | "setIncreaseDebtForbidden"
      | "setLimitPerBlock"
      | "setLimits"
      | "setLiquidationThreshold"
      | "setMaxEnabledTokens"
      | "underlying"
      | "upgradeCreditConfigurator"
      | "upgradeCreditFacade"
      | "upgradePriceOracle"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addCollateralToken",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "addEmergencyLiquidator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addressProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowContract",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "allowToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditFacade",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forbidAdapter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "forbidContract",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "forbidToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmergencyLiquidator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpirationDate",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setIncreaseDebtForbidden",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLimitPerBlock",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLimits",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLiquidationThreshold",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxEnabledTokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "underlying",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeCreditConfigurator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeCreditFacade",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradePriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addEmergencyLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowedContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditFacade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forbidAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forbidContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forbidToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeEmergencyLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpirationDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIncreaseDebtForbidden",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLimitPerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setLimits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxEnabledTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "underlying", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeCreditConfigurator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeCreditFacade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradePriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "AdapterForbidden(address)": EventFragment;
    "AddedToUpgradeable(address)": EventFragment;
    "ContractAllowed(address,address)": EventFragment;
    "ContractForbidden(address)": EventFragment;
    "CreditConfiguratorUpgraded(address)": EventFragment;
    "CreditFacadeUpgraded(address)": EventFragment;
    "CumulativeLossReset()": EventFragment;
    "EmergencyLiquidatorAdded(address)": EventFragment;
    "EmergencyLiquidatorRemoved(address)": EventFragment;
    "ExpirationDateUpdated(uint40)": EventFragment;
    "FeesUpdated(uint16,uint16,uint16,uint16,uint16)": EventFragment;
    "IncreaseDebtForbiddenModeChanged(bool)": EventFragment;
    "LimitPerBlockUpdated(uint128)": EventFragment;
    "LimitsUpdated(uint256,uint256)": EventFragment;
    "MaxEnabledTokensUpdated(uint8)": EventFragment;
    "NewEmergencyLiquidationDiscount(uint16)": EventFragment;
    "NewMaxCumulativeLoss(uint128)": EventFragment;
    "NewTotalDebtLimit(uint128)": EventFragment;
    "PriceOracleUpgraded(address)": EventFragment;
    "RemovedFromUpgradeable(address)": EventFragment;
    "TokenAllowed(address)": EventFragment;
    "TokenForbidden(address)": EventFragment;
    "TokenLiquidationThresholdUpdated(address,uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdapterForbidden"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddedToUpgradeable"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractAllowed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractForbidden"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreditConfiguratorUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreditFacadeUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CumulativeLossReset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyLiquidatorAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyLiquidatorRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExpirationDateUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeesUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "IncreaseDebtForbiddenModeChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LimitPerBlockUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LimitsUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MaxEnabledTokensUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewEmergencyLiquidationDiscount"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewMaxCumulativeLoss"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewTotalDebtLimit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceOracleUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemovedFromUpgradeable"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenAllowed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenForbidden"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "TokenLiquidationThresholdUpdated"
  ): EventFragment;
}

export interface AdapterForbiddenEventObject {
  adapter: string;
}
export type AdapterForbiddenEvent = TypedEvent<
  [string],
  AdapterForbiddenEventObject
>;

export type AdapterForbiddenEventFilter =
  TypedEventFilter<AdapterForbiddenEvent>;

export interface AddedToUpgradeableEventObject {
  arg0: string;
}
export type AddedToUpgradeableEvent = TypedEvent<
  [string],
  AddedToUpgradeableEventObject
>;

export type AddedToUpgradeableEventFilter =
  TypedEventFilter<AddedToUpgradeableEvent>;

export interface ContractAllowedEventObject {
  protocol: string;
  adapter: string;
}
export type ContractAllowedEvent = TypedEvent<
  [string, string],
  ContractAllowedEventObject
>;

export type ContractAllowedEventFilter = TypedEventFilter<ContractAllowedEvent>;

export interface ContractForbiddenEventObject {
  protocol: string;
}
export type ContractForbiddenEvent = TypedEvent<
  [string],
  ContractForbiddenEventObject
>;

export type ContractForbiddenEventFilter =
  TypedEventFilter<ContractForbiddenEvent>;

export interface CreditConfiguratorUpgradedEventObject {
  newCreditConfigurator: string;
}
export type CreditConfiguratorUpgradedEvent = TypedEvent<
  [string],
  CreditConfiguratorUpgradedEventObject
>;

export type CreditConfiguratorUpgradedEventFilter =
  TypedEventFilter<CreditConfiguratorUpgradedEvent>;

export interface CreditFacadeUpgradedEventObject {
  newCreditFacade: string;
}
export type CreditFacadeUpgradedEvent = TypedEvent<
  [string],
  CreditFacadeUpgradedEventObject
>;

export type CreditFacadeUpgradedEventFilter =
  TypedEventFilter<CreditFacadeUpgradedEvent>;

export interface CumulativeLossResetEventObject {}
export type CumulativeLossResetEvent = TypedEvent<
  [],
  CumulativeLossResetEventObject
>;

export type CumulativeLossResetEventFilter =
  TypedEventFilter<CumulativeLossResetEvent>;

export interface EmergencyLiquidatorAddedEventObject {
  arg0: string;
}
export type EmergencyLiquidatorAddedEvent = TypedEvent<
  [string],
  EmergencyLiquidatorAddedEventObject
>;

export type EmergencyLiquidatorAddedEventFilter =
  TypedEventFilter<EmergencyLiquidatorAddedEvent>;

export interface EmergencyLiquidatorRemovedEventObject {
  arg0: string;
}
export type EmergencyLiquidatorRemovedEvent = TypedEvent<
  [string],
  EmergencyLiquidatorRemovedEventObject
>;

export type EmergencyLiquidatorRemovedEventFilter =
  TypedEventFilter<EmergencyLiquidatorRemovedEvent>;

export interface ExpirationDateUpdatedEventObject {
  arg0: number;
}
export type ExpirationDateUpdatedEvent = TypedEvent<
  [number],
  ExpirationDateUpdatedEventObject
>;

export type ExpirationDateUpdatedEventFilter =
  TypedEventFilter<ExpirationDateUpdatedEvent>;

export interface FeesUpdatedEventObject {
  feeInterest: number;
  feeLiquidation: number;
  liquidationPremium: number;
  feeLiquidationExpired: number;
  liquidationPremiumExpired: number;
}
export type FeesUpdatedEvent = TypedEvent<
  [number, number, number, number, number],
  FeesUpdatedEventObject
>;

export type FeesUpdatedEventFilter = TypedEventFilter<FeesUpdatedEvent>;

export interface IncreaseDebtForbiddenModeChangedEventObject {
  arg0: boolean;
}
export type IncreaseDebtForbiddenModeChangedEvent = TypedEvent<
  [boolean],
  IncreaseDebtForbiddenModeChangedEventObject
>;

export type IncreaseDebtForbiddenModeChangedEventFilter =
  TypedEventFilter<IncreaseDebtForbiddenModeChangedEvent>;

export interface LimitPerBlockUpdatedEventObject {
  arg0: BigNumber;
}
export type LimitPerBlockUpdatedEvent = TypedEvent<
  [BigNumber],
  LimitPerBlockUpdatedEventObject
>;

export type LimitPerBlockUpdatedEventFilter =
  TypedEventFilter<LimitPerBlockUpdatedEvent>;

export interface LimitsUpdatedEventObject {
  minBorrowedAmount: BigNumber;
  maxBorrowedAmount: BigNumber;
}
export type LimitsUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  LimitsUpdatedEventObject
>;

export type LimitsUpdatedEventFilter = TypedEventFilter<LimitsUpdatedEvent>;

export interface MaxEnabledTokensUpdatedEventObject {
  arg0: number;
}
export type MaxEnabledTokensUpdatedEvent = TypedEvent<
  [number],
  MaxEnabledTokensUpdatedEventObject
>;

export type MaxEnabledTokensUpdatedEventFilter =
  TypedEventFilter<MaxEnabledTokensUpdatedEvent>;

export interface NewEmergencyLiquidationDiscountEventObject {
  arg0: number;
}
export type NewEmergencyLiquidationDiscountEvent = TypedEvent<
  [number],
  NewEmergencyLiquidationDiscountEventObject
>;

export type NewEmergencyLiquidationDiscountEventFilter =
  TypedEventFilter<NewEmergencyLiquidationDiscountEvent>;

export interface NewMaxCumulativeLossEventObject {
  arg0: BigNumber;
}
export type NewMaxCumulativeLossEvent = TypedEvent<
  [BigNumber],
  NewMaxCumulativeLossEventObject
>;

export type NewMaxCumulativeLossEventFilter =
  TypedEventFilter<NewMaxCumulativeLossEvent>;

export interface NewTotalDebtLimitEventObject {
  arg0: BigNumber;
}
export type NewTotalDebtLimitEvent = TypedEvent<
  [BigNumber],
  NewTotalDebtLimitEventObject
>;

export type NewTotalDebtLimitEventFilter =
  TypedEventFilter<NewTotalDebtLimitEvent>;

export interface PriceOracleUpgradedEventObject {
  newPriceOracle: string;
}
export type PriceOracleUpgradedEvent = TypedEvent<
  [string],
  PriceOracleUpgradedEventObject
>;

export type PriceOracleUpgradedEventFilter =
  TypedEventFilter<PriceOracleUpgradedEvent>;

export interface RemovedFromUpgradeableEventObject {
  arg0: string;
}
export type RemovedFromUpgradeableEvent = TypedEvent<
  [string],
  RemovedFromUpgradeableEventObject
>;

export type RemovedFromUpgradeableEventFilter =
  TypedEventFilter<RemovedFromUpgradeableEvent>;

export interface TokenAllowedEventObject {
  token: string;
}
export type TokenAllowedEvent = TypedEvent<[string], TokenAllowedEventObject>;

export type TokenAllowedEventFilter = TypedEventFilter<TokenAllowedEvent>;

export interface TokenForbiddenEventObject {
  token: string;
}
export type TokenForbiddenEvent = TypedEvent<
  [string],
  TokenForbiddenEventObject
>;

export type TokenForbiddenEventFilter = TypedEventFilter<TokenForbiddenEvent>;

export interface TokenLiquidationThresholdUpdatedEventObject {
  token: string;
  liquidityThreshold: number;
}
export type TokenLiquidationThresholdUpdatedEvent = TypedEvent<
  [string, number],
  TokenLiquidationThresholdUpdatedEventObject
>;

export type TokenLiquidationThresholdUpdatedEventFilter =
  TypedEventFilter<TokenLiquidationThresholdUpdatedEvent>;

export interface ICreditConfigurator extends BaseContract {
  contractName: "ICreditConfigurator";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICreditConfiguratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addCollateralToken(
      token: PromiseOrValue<string>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addEmergencyLiquidator(
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addressProvider(overrides?: CallOverrides): Promise<[string]>;

    allowContract(
      targetContract: PromiseOrValue<string>,
      adapter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    allowToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    allowedContracts(overrides?: CallOverrides): Promise<[string[]]>;

    creditFacade(overrides?: CallOverrides): Promise<[string]>;

    creditManager(overrides?: CallOverrides): Promise<[string]>;

    forbidAdapter(
      adapter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    forbidContract(
      targetContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    forbidToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeEmergencyLiquidator(
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setExpirationDate(
      newExpirationDate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFees(
      _feeInterest: PromiseOrValue<BigNumberish>,
      _feeLiquidation: PromiseOrValue<BigNumberish>,
      _liquidationPremium: PromiseOrValue<BigNumberish>,
      _feeLiquidationExpired: PromiseOrValue<BigNumberish>,
      _liquidationPremiumExpired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setIncreaseDebtForbidden(
      _mode: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLimitPerBlock(
      newLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLimits(
      _minBorrowedAmount: PromiseOrValue<BigNumberish>,
      _maxBorrowedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLiquidationThreshold(
      token: PromiseOrValue<string>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMaxEnabledTokens(
      maxEnabledTokens: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    underlying(overrides?: CallOverrides): Promise<[string]>;

    upgradeCreditConfigurator(
      _creditConfigurator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeCreditFacade(
      _creditFacade: PromiseOrValue<string>,
      migrateParams: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradePriceOracle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addCollateralToken(
    token: PromiseOrValue<string>,
    liquidationThreshold: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addEmergencyLiquidator(
    liquidator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addressProvider(overrides?: CallOverrides): Promise<string>;

  allowContract(
    targetContract: PromiseOrValue<string>,
    adapter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  allowToken(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  allowedContracts(overrides?: CallOverrides): Promise<string[]>;

  creditFacade(overrides?: CallOverrides): Promise<string>;

  creditManager(overrides?: CallOverrides): Promise<string>;

  forbidAdapter(
    adapter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  forbidContract(
    targetContract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  forbidToken(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeEmergencyLiquidator(
    liquidator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setExpirationDate(
    newExpirationDate: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFees(
    _feeInterest: PromiseOrValue<BigNumberish>,
    _feeLiquidation: PromiseOrValue<BigNumberish>,
    _liquidationPremium: PromiseOrValue<BigNumberish>,
    _feeLiquidationExpired: PromiseOrValue<BigNumberish>,
    _liquidationPremiumExpired: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setIncreaseDebtForbidden(
    _mode: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLimitPerBlock(
    newLimit: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLimits(
    _minBorrowedAmount: PromiseOrValue<BigNumberish>,
    _maxBorrowedAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLiquidationThreshold(
    token: PromiseOrValue<string>,
    liquidationThreshold: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMaxEnabledTokens(
    maxEnabledTokens: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  underlying(overrides?: CallOverrides): Promise<string>;

  upgradeCreditConfigurator(
    _creditConfigurator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeCreditFacade(
    _creditFacade: PromiseOrValue<string>,
    migrateParams: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradePriceOracle(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addCollateralToken(
      token: PromiseOrValue<string>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    addEmergencyLiquidator(
      liquidator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addressProvider(overrides?: CallOverrides): Promise<string>;

    allowContract(
      targetContract: PromiseOrValue<string>,
      adapter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    allowToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    allowedContracts(overrides?: CallOverrides): Promise<string[]>;

    creditFacade(overrides?: CallOverrides): Promise<string>;

    creditManager(overrides?: CallOverrides): Promise<string>;

    forbidAdapter(
      adapter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    forbidContract(
      targetContract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    forbidToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeEmergencyLiquidator(
      liquidator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setExpirationDate(
      newExpirationDate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFees(
      _feeInterest: PromiseOrValue<BigNumberish>,
      _feeLiquidation: PromiseOrValue<BigNumberish>,
      _liquidationPremium: PromiseOrValue<BigNumberish>,
      _feeLiquidationExpired: PromiseOrValue<BigNumberish>,
      _liquidationPremiumExpired: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setIncreaseDebtForbidden(
      _mode: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLimitPerBlock(
      newLimit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLimits(
      _minBorrowedAmount: PromiseOrValue<BigNumberish>,
      _maxBorrowedAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLiquidationThreshold(
      token: PromiseOrValue<string>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxEnabledTokens(
      maxEnabledTokens: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    underlying(overrides?: CallOverrides): Promise<string>;

    upgradeCreditConfigurator(
      _creditConfigurator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeCreditFacade(
      _creditFacade: PromiseOrValue<string>,
      migrateParams: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradePriceOracle(overrides?: CallOverrides): Promise<void>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "AdapterForbidden(address)"(
      adapter?: PromiseOrValue<string> | null
    ): AdapterForbiddenEventFilter;
    AdapterForbidden(
      adapter?: PromiseOrValue<string> | null
    ): AdapterForbiddenEventFilter;

    "AddedToUpgradeable(address)"(arg0?: null): AddedToUpgradeableEventFilter;
    AddedToUpgradeable(arg0?: null): AddedToUpgradeableEventFilter;

    "ContractAllowed(address,address)"(
      protocol?: PromiseOrValue<string> | null,
      adapter?: PromiseOrValue<string> | null
    ): ContractAllowedEventFilter;
    ContractAllowed(
      protocol?: PromiseOrValue<string> | null,
      adapter?: PromiseOrValue<string> | null
    ): ContractAllowedEventFilter;

    "ContractForbidden(address)"(
      protocol?: PromiseOrValue<string> | null
    ): ContractForbiddenEventFilter;
    ContractForbidden(
      protocol?: PromiseOrValue<string> | null
    ): ContractForbiddenEventFilter;

    "CreditConfiguratorUpgraded(address)"(
      newCreditConfigurator?: PromiseOrValue<string> | null
    ): CreditConfiguratorUpgradedEventFilter;
    CreditConfiguratorUpgraded(
      newCreditConfigurator?: PromiseOrValue<string> | null
    ): CreditConfiguratorUpgradedEventFilter;

    "CreditFacadeUpgraded(address)"(
      newCreditFacade?: PromiseOrValue<string> | null
    ): CreditFacadeUpgradedEventFilter;
    CreditFacadeUpgraded(
      newCreditFacade?: PromiseOrValue<string> | null
    ): CreditFacadeUpgradedEventFilter;

    "CumulativeLossReset()"(): CumulativeLossResetEventFilter;
    CumulativeLossReset(): CumulativeLossResetEventFilter;

    "EmergencyLiquidatorAdded(address)"(
      arg0?: null
    ): EmergencyLiquidatorAddedEventFilter;
    EmergencyLiquidatorAdded(arg0?: null): EmergencyLiquidatorAddedEventFilter;

    "EmergencyLiquidatorRemoved(address)"(
      arg0?: null
    ): EmergencyLiquidatorRemovedEventFilter;
    EmergencyLiquidatorRemoved(
      arg0?: null
    ): EmergencyLiquidatorRemovedEventFilter;

    "ExpirationDateUpdated(uint40)"(
      arg0?: null
    ): ExpirationDateUpdatedEventFilter;
    ExpirationDateUpdated(arg0?: null): ExpirationDateUpdatedEventFilter;

    "FeesUpdated(uint16,uint16,uint16,uint16,uint16)"(
      feeInterest?: null,
      feeLiquidation?: null,
      liquidationPremium?: null,
      feeLiquidationExpired?: null,
      liquidationPremiumExpired?: null
    ): FeesUpdatedEventFilter;
    FeesUpdated(
      feeInterest?: null,
      feeLiquidation?: null,
      liquidationPremium?: null,
      feeLiquidationExpired?: null,
      liquidationPremiumExpired?: null
    ): FeesUpdatedEventFilter;

    "IncreaseDebtForbiddenModeChanged(bool)"(
      arg0?: null
    ): IncreaseDebtForbiddenModeChangedEventFilter;
    IncreaseDebtForbiddenModeChanged(
      arg0?: null
    ): IncreaseDebtForbiddenModeChangedEventFilter;

    "LimitPerBlockUpdated(uint128)"(
      arg0?: null
    ): LimitPerBlockUpdatedEventFilter;
    LimitPerBlockUpdated(arg0?: null): LimitPerBlockUpdatedEventFilter;

    "LimitsUpdated(uint256,uint256)"(
      minBorrowedAmount?: null,
      maxBorrowedAmount?: null
    ): LimitsUpdatedEventFilter;
    LimitsUpdated(
      minBorrowedAmount?: null,
      maxBorrowedAmount?: null
    ): LimitsUpdatedEventFilter;

    "MaxEnabledTokensUpdated(uint8)"(
      arg0?: null
    ): MaxEnabledTokensUpdatedEventFilter;
    MaxEnabledTokensUpdated(arg0?: null): MaxEnabledTokensUpdatedEventFilter;

    "NewEmergencyLiquidationDiscount(uint16)"(
      arg0?: null
    ): NewEmergencyLiquidationDiscountEventFilter;
    NewEmergencyLiquidationDiscount(
      arg0?: null
    ): NewEmergencyLiquidationDiscountEventFilter;

    "NewMaxCumulativeLoss(uint128)"(
      arg0?: null
    ): NewMaxCumulativeLossEventFilter;
    NewMaxCumulativeLoss(arg0?: null): NewMaxCumulativeLossEventFilter;

    "NewTotalDebtLimit(uint128)"(arg0?: null): NewTotalDebtLimitEventFilter;
    NewTotalDebtLimit(arg0?: null): NewTotalDebtLimitEventFilter;

    "PriceOracleUpgraded(address)"(
      newPriceOracle?: PromiseOrValue<string> | null
    ): PriceOracleUpgradedEventFilter;
    PriceOracleUpgraded(
      newPriceOracle?: PromiseOrValue<string> | null
    ): PriceOracleUpgradedEventFilter;

    "RemovedFromUpgradeable(address)"(
      arg0?: null
    ): RemovedFromUpgradeableEventFilter;
    RemovedFromUpgradeable(arg0?: null): RemovedFromUpgradeableEventFilter;

    "TokenAllowed(address)"(
      token?: PromiseOrValue<string> | null
    ): TokenAllowedEventFilter;
    TokenAllowed(
      token?: PromiseOrValue<string> | null
    ): TokenAllowedEventFilter;

    "TokenForbidden(address)"(
      token?: PromiseOrValue<string> | null
    ): TokenForbiddenEventFilter;
    TokenForbidden(
      token?: PromiseOrValue<string> | null
    ): TokenForbiddenEventFilter;

    "TokenLiquidationThresholdUpdated(address,uint16)"(
      token?: PromiseOrValue<string> | null,
      liquidityThreshold?: null
    ): TokenLiquidationThresholdUpdatedEventFilter;
    TokenLiquidationThresholdUpdated(
      token?: PromiseOrValue<string> | null,
      liquidityThreshold?: null
    ): TokenLiquidationThresholdUpdatedEventFilter;
  };

  estimateGas: {
    addCollateralToken(
      token: PromiseOrValue<string>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addEmergencyLiquidator(
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addressProvider(overrides?: CallOverrides): Promise<BigNumber>;

    allowContract(
      targetContract: PromiseOrValue<string>,
      adapter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    allowToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    allowedContracts(overrides?: CallOverrides): Promise<BigNumber>;

    creditFacade(overrides?: CallOverrides): Promise<BigNumber>;

    creditManager(overrides?: CallOverrides): Promise<BigNumber>;

    forbidAdapter(
      adapter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    forbidContract(
      targetContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    forbidToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeEmergencyLiquidator(
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setExpirationDate(
      newExpirationDate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFees(
      _feeInterest: PromiseOrValue<BigNumberish>,
      _feeLiquidation: PromiseOrValue<BigNumberish>,
      _liquidationPremium: PromiseOrValue<BigNumberish>,
      _feeLiquidationExpired: PromiseOrValue<BigNumberish>,
      _liquidationPremiumExpired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setIncreaseDebtForbidden(
      _mode: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLimitPerBlock(
      newLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLimits(
      _minBorrowedAmount: PromiseOrValue<BigNumberish>,
      _maxBorrowedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLiquidationThreshold(
      token: PromiseOrValue<string>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMaxEnabledTokens(
      maxEnabledTokens: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    underlying(overrides?: CallOverrides): Promise<BigNumber>;

    upgradeCreditConfigurator(
      _creditConfigurator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeCreditFacade(
      _creditFacade: PromiseOrValue<string>,
      migrateParams: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradePriceOracle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addCollateralToken(
      token: PromiseOrValue<string>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addEmergencyLiquidator(
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addressProvider(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allowContract(
      targetContract: PromiseOrValue<string>,
      adapter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    allowToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    allowedContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    creditFacade(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    creditManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    forbidAdapter(
      adapter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    forbidContract(
      targetContract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    forbidToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeEmergencyLiquidator(
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setExpirationDate(
      newExpirationDate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFees(
      _feeInterest: PromiseOrValue<BigNumberish>,
      _feeLiquidation: PromiseOrValue<BigNumberish>,
      _liquidationPremium: PromiseOrValue<BigNumberish>,
      _feeLiquidationExpired: PromiseOrValue<BigNumberish>,
      _liquidationPremiumExpired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setIncreaseDebtForbidden(
      _mode: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLimitPerBlock(
      newLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLimits(
      _minBorrowedAmount: PromiseOrValue<BigNumberish>,
      _maxBorrowedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLiquidationThreshold(
      token: PromiseOrValue<string>,
      liquidationThreshold: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMaxEnabledTokens(
      maxEnabledTokens: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    underlying(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    upgradeCreditConfigurator(
      _creditConfigurator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeCreditFacade(
      _creditFacade: PromiseOrValue<string>,
      migrateParams: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradePriceOracle(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
