/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDataCompressor } from "./IDataCompressor";
export type { IDataCompressorExceptions } from "./IDataCompressorExceptions";
