/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20ApproveRestrictedFalse } from "./ERC20ApproveRestrictedFalse";
export type { ERC20ApproveRestrictedRevert } from "./ERC20ApproveRestrictedRevert";
