/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IContractsRegister } from "./IContractsRegister";
export type { IContractsRegisterEvents } from "./IContractsRegisterEvents";
